### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by karai17** [karai17/lapis-chan#11]
There are a lot of hard-coded strings in the code right now, it would be nice to pull those out into a `strings` file and use an i18n library to support multiple languages.

**Comment by qaisjp** [comment]
check out @kikito's [library](https://github.com/kikito/i18n.lua)

**Comment by karai17** [comment]
Aye, I have my own i18n library I whipped together during Ludum Dare 33, but I believe @kikito's is more feature complete. I'll be sure to investigate it, thanks!

**Comment by karai17** [comment]
Commit 1e12228 has a significant chunk of i18n support, but it is not yet finished. I still need to go through each and every view to pull out language. I have an idea on how I want to deal with HTML tags so we'll see how that goes.

I decided to use @kikito's module as it is far more advanced than my own and has a pretty nice API.

**Comment by josefnpat** [comment]
:+1:
