### ISSUE TITLE
Increase comment character limit

### ISSUE THREAD

**Issue by karai17** [karai17/lapis-chan#32]
Limit is currently 4096, some people are saying it is not enough. Bumping it up to 10k or even 20k should be good.

It would also be nice to add an option in the config file instead of having to dig around in several files up update if someone wants to customize it on their own site.

**Comment by josefnpat** [comment]
I think you ought to use the SQL types `[TINY|MEDIUM|LONG]TEXT` for this. I'm assuming you're using `VAR CHAR(4096)`, so I would suggest one of the following from a performance standpoint.

I think 4chan uses TEXT (65k)

```
      Type | Maximum length
-----------+-------------------------------------
  TINYTEXT |           255 (2 8−1) bytes
      TEXT |        65,535 (216−1) bytes = 64 KiB
MEDIUMTEXT |    16,777,215 (224−1) bytes = 16 MiB
  LONGTEXT | 4,294,967,295 (232−1) bytes =  4 GiB
```

**Comment by karai17** [comment]
I'm just using the basic types that Lapis provides, so varchar(255)s and text 64k.

**Comment by josefnpat** [comment]
but `TEXT` has a 65k limit. Why not just use that?

**Comment by karai17** [comment]
I am! it was a typo.
