### ISSUE TITLE
Bluetext

### ISSUE THREAD

**Issue by josefnpat** [karai17/lapis-chan#33]
Here's a patch for bluetext: http://pastebin.com/raw/PS4J6rz9

Not sure if it works, would be nice if someone tested it

Relates to #31

**Comment by unek** [comment]
+1 we need this

**Comment by karai17** [comment]
$20 USD, as per my agreement with @feilkin

:D

**Comment by josefnpat** [comment]
_Or someone can maintain a patchset against the codebase / fork the software considering it's MIT._

Anyway, dickery aside, why not add checkboxes to the install or lines in the config that enable and disable these features? I can understand not wanting bluetext on lapchan.moe, but these seem to be real features that folks want.

**Comment by shakesoda** [comment]
@josefnpat very minor typo in the patch: still says >implying instead of <implying

that said, I don't really care either way about this, but I prefer keeping the formatting for non-mod posts as simple as possible and so far the only argument for bluetext has been for shitposting.

**Comment by karai17** [comment]
I promised @unek that I would wave the $20 fee if he added a polski translation.

**Comment by josefnpat** [comment]
@shakesoda thanks for noticing; updated: http://pastebin.com/raw/0tNegSge
