### ISSUE TITLE
webm support

### ISSUE THREAD

**Issue by shakesoda** [karai17/lapis-chan#42]
> 2016
> no webm support

**Comment by karai17** [comment]
FWIW IE still doesn't support WEBM or WEBP. I don't mind adding it, but it could be an an issue. Does ImageMagick support webm/p?

**Comment by shakesoda** [comment]
IE is irrelevant and every other chan these days supports webm, so who cares.

I think imagemagick does support getting frames out of webm's.

**Comment by karai17** [comment]
Now works! Depends on FFmpeg, though.
