### ISSUE TITLE
Replace most CSS 6-digit hex colors for 3-digit equivalents

### ISSUE THREAD

**Issue by PVNFU-28** [karai17/lapis-chan#62]
"Some six-digit hex colors can be written using a three-digit shorthand. Three-digit shorthand is where you combine the duplicate digits from each color component into one."

#RRGGBB = #RGB 
#000000 = #000

If done to every css file this will save some file size and bandwidth, this can't be done to values like #FC0456 or #FFCC91 though.

**Comment by karai17** [comment]
I can understand where this is coming from, but over all I don't think saving a few bytes on an uncached request is worth the ambiguity, especially since it can only be applied to a few rules at most.

**Comment by PVNFU-28** [comment]
It's fine but I don't think ther is ambiguity and when it comes to websites saving bandwidth is always nice for both the owner and users.
But again, it's fine.
